[tool.ruff]
 target-version = 'py310'
 line-length = 88
 respect-gitignore = true
 ignore-init-module-imports = true
 show-fixes = true
 
 select = [
     "ANN", #flake8-annotations
     "A", # flake8-builtins
     "BLE", # flake8-blind-except
     "C4", # flake8-comprehensions
     "C90", # mccabe
     "DTZ", # flake8-datetimesz
     "COM", # flake8-commas
     "ERA", # eradicate
     "I", #isort
     "E", # Error
     "F", # pyflakes
     "ICN", # flake8-import-conventions
     "ISC", # flake8-implicit-str-concat
     "N", # pep8-naming
     "PD", # pandas-vet
     "PIE", # flake8-pie
     "PT", # flake8-pytest-style
     "PTH", # flake8-use-pathlib
     "Q", # flake8-quotes
     "RSE", #flake8-raise
     "RET", #flake-return
     "SIM", # flake8-simplify
     "T20", # flake8-print
     "TID", # flake8-tidy-imports
     "UP", # pyupgrade
     "W", # Warning
 ]
 
 # Allow fix for all enabled rules (when --fix) is provided. (only safes fixes will be applied)
 fixable = ["ALL"]
 unfixable = []
 
 [tool.ruff.mccabe]
 max-complexity = 5 # This is currently not in use as a function is raising issues.
 
 [tool.ruff.flake8-quotes]
 inline-quotes = "double"
 
 [tool.ruff.format]
 quote-style = "double"
 indent-style = "space"
 skip-magic-trailing-comma = false
 line-ending = "auto"